version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: siuras
      POSTGRES_PASSWORD: siuras
      POSTGRES_DB: siuras
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"